data_dir = "./spacio_training_2"
data_set = "processed_actual_V"
model_name = "new_model"

# hyperparameters
train_epochs = 1 #20
img_size = 1024
in_channels = 1
out_channels = 3
embd_channels = 64#256
patch_size = 16#8
f_hidden = 4#8
neighbourhood = 1#7
n_layers = 1#10
learning_rate = 0.0001270083664733935
gamma = 0.3
step_size = 5